local t = require("tests.test_helper")
local panel = require("nx.panel")

t.describe("panel.add_buffer", function()
  t.it("tracks a buffer with a label", function()
    panel.reset()
    panel.add_buffer(101, "my-app:serve")
    local bufs = panel.list_buffers()
    t.assert_eq(1, #bufs)
    t.assert_eq(101, bufs[1].buf)
    t.assert_eq("my-app:serve", bufs[1].label)
  end)
end)

t.describe("panel.remove_buffer", function()
  t.it("removes a buffer by bufnr", function()
    panel.reset()
    panel.add_buffer(101, "my-app:serve")
    panel.add_buffer(102, "my-app:build")
    panel.remove_buffer(101)
    local bufs = panel.list_buffers()
    t.assert_eq(1, #bufs)
    t.assert_eq(102, bufs[1].buf)
  end)
end)

t.describe("panel.get_active", function()
  t.it("returns the most recently added buffer by default", function()
    panel.reset()
    panel.add_buffer(101, "my-app:serve")
    panel.add_buffer(102, "my-app:build")
    local active = panel.get_active()
    t.assert_eq(102, active.buf)
  end)
end)

t.describe("panel.select_buffer", function()
  t.it("changes the active buffer", function()
    panel.reset()
    panel.add_buffer(101, "a")
    panel.add_buffer(102, "b")
    panel.select_buffer(101)
    t.assert_eq(101, panel.get_active().buf)
  end)
end)

t.describe("panel.next_buffer and prev_buffer", function()
  t.it("cycles through buffers", function()
    panel.reset()
    panel.add_buffer(101, "a")
    panel.add_buffer(102, "b")
    panel.add_buffer(103, "c")
    panel.select_buffer(101)
    panel.next_buffer()
    t.assert_eq(102, panel.get_active().buf)
    panel.next_buffer()
    t.assert_eq(103, panel.get_active().buf)
    panel.next_buffer()
    t.assert_eq(101, panel.get_active().buf)
  end)

  t.it("cycles backward", function()
    panel.reset()
    panel.add_buffer(101, "a")
    panel.add_buffer(102, "b")
    panel.select_buffer(101)
    panel.prev_buffer()
    t.assert_eq(102, panel.get_active().buf)
  end)
end)

t.done()
